sudo: required
services:
  - docker

# before install gonna have a series of cmds
# executed b4 our tests are ran
before_install:
  - docker build -t znoori455/docker-react -f Dockerfile.dev .

# script section contains all the diff cmds
# that need to be executed to actually run our test suite
# each cmd denoted by - must return 0 ; else travis assumes
# our code is brokeded
script:
  - docker run -e CI=true znoori455/docker-react npm run test

# tells travis ci how to take app and deploy to aws
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-403594414960"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"